services:
  app-springboot:
    build: .
    container_name: app-concesionaria-automoviles-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_concesionaria_automoviles
      - SPRING_DATASOURCE_USERNAME=f978bdea
      - SPRING_DATASOURCE_PASSWORD=b24317af
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: f978bdea
      POSTGRES_PASSWORD: b24317af
      POSTGRES_DB: db_concesionaria_automoviles
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: