spring.application.name=consecionaria-automoviles

# Conexion JDBC con modo PostgreSQL activo
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=credencial_usuario
spring.datasource.password=credencial_contrasenia

# Consola H2 (opcional, para ver los datos en /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracion de Hibernate para que genere SQL compatible con Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true